use super::*;

use crate::catalog;


pub static IRONCORE: EngineProfile = EngineProfile {
    key: "ironcore",
    format: Format::Xml,
    label: "Ironcore",
    blurb: "raceid, species, the pacifist system, CONST_ME_* effects",
    raceid_attr: Some("raceid"),
    has_species: true,
    has_bestiary: false,
    races: RACES_5,
    skulls: SKULLS_7,
    recursive_corpus: false,
    has_registry: true,
    extension: "xml",
    look_addons: true,
    look_mount: true,
    look_corpseactionid: true,
    bool_flags: catalog::BOOL_FLAGS,
    num_flags: catalog::NUM_FLAGS,
    dead_flags: &[],
    has_pacifist: true,
    pushable_override: PushableOverride::Always,
    clamps_health: true,
    immunities: IMMUNITIES_10,
    elements: ELEMENTS_10,
    target_strategy: None,
    target_strategy_sums_100: false,
    warns_missing_target_strategy: false,
    cadence: Cadence::Interval,
    builtin_spells: catalog::BUILTIN_SPELLS,
    melee: MeleeKind::SpellBlock,
    melee_conditions: MELEE_COND_FULL,
    melee_skill_progression: false,
    geometry_ring: true,
    speed_spell: SpeedSpell::SpeedChange,
    condition_spell: ConditionSpell::TickStart,
    range_limit: RangeLimit::ClampTo(catalog::MAX_SPELL_RANGE),
    spell_range_default: 0,
    effect_naming: EffectNaming::ConstMe,
    magic_effects: catalog::MAGIC_EFFECTS,
    shoot_effects: catalog::SHOOT_EFFECTS,
    spell_effect_keys: catalog::SPELL_EFFECT_KEYS,
    summon_effect_keys: catalog::SUMMON_EFFECT_KEYS,
    loot_inside_wrapper: true,
    loot_validates_ids: true,
    loot_countmax_max: Some(catalog::MAX_LOOT_COUNTMAX),
    warns_missing_targetchange_interval: true,
    summon_interval: true,
    summon_delay: false,
    summon_max_key: "max",
    summon_nested: false,
    voices_interval: true,
    voices_chance: true,
    suppressed_lints: &[],
};

pub static TFS: EngineProfile = EngineProfile {
    key: "tfs",
    format: Format::Xml,
    label: "TheForgottenServer 1.x",
    blurb: "raceId + <bestiary>, short-name effects, no pacifist system",
    // The polarity of Ironcore's `raceid.wrong-case` lint inverts here
    // (`monsters.cpp:874`).
    raceid_attr: Some("raceId"),
    has_species: false,
    has_bestiary: true,
    races: RACES_TFS,
    skulls: SKULLS_7,
    recursive_corpus: true,
    has_registry: true,
    extension: "xml",
    look_addons: true,
    look_mount: true,
    look_corpseactionid: false,
    bool_flags: &[
        "attackable",
        "hostile",
        "summonable",
        "convinceable",
        "illusionable",
        "challengeable",
        "pushable",
        "canpushitems",
        "canpushcreatures",
        "isboss",
        "ignorespawnblock",
        "hidehealth",
        "canwalkonenergy",
        "canwalkonfire",
        "canwalkonpoison",
    ],
    num_flags: &[
        "staticattack",
        "targetdistance",
        "runonhealth",
        "lightlevel",
        "lightcolor",
    ],
    dead_flags: &[],
    has_pacifist: false,
    pushable_override: PushableOverride::Always,
    clamps_health: true,
    immunities: IMMUNITIES_10,
    elements: ELEMENTS_10,
    target_strategy: None,
    target_strategy_sums_100: false,
    warns_missing_target_strategy: false,
    cadence: Cadence::Interval,
    builtin_spells: SPELLS_TFS,
    melee: MeleeKind::SpellBlock,
    melee_conditions: MELEE_COND_FULL,
    melee_skill_progression: false,
    geometry_ring: true,
    speed_spell: SpeedSpell::SpeedChange,
    condition_spell: ConditionSpell::TickStart,
    range_limit: RangeLimit::ClampTo(22),
    spell_range_default: 0,
    effect_naming: EffectNaming::ShortName,
    magic_effects: ME_TFS,
    shoot_effects: ANI_TFS,
    // No `aoeShootEffect` — anything but these two logs "does not exist"
    // (`monsters.cpp:533`).
    spell_effect_keys: &["shootEffect", "areaEffect"],
    summon_effect_keys: &["effect", "masterEffect"],
    loot_inside_wrapper: true,
    loot_validates_ids: true,
    loot_countmax_max: None,
    warns_missing_targetchange_interval: true,
    summon_interval: true,
    summon_delay: false,
    summon_max_key: "max",
    summon_nested: false,
    voices_interval: true,
    voices_chance: true,
    suppressed_lints: &[
        // No pacifist system at all.
        "flag.pacifist-forces-hostile-off",
        "flag.pacifist-subflag-without-pacifist",
        // Ironcore's knife/pitchfork sprite quirk is a CONST_ANI_* value.
        "effect.knife-renders-pitchfork",
    ],
};

pub static TVP: EngineProfile = EngineProfile {
    key: "tvp",
    format: Format::Xml,
    label: "TheVioletProject",
    blurb: "7.x: <targetstrategy>, delay=, melee skill progression",
    raceid_attr: None,
    has_species: false,
    has_bestiary: false,
    races: RACES_5,
    skulls: SKULLS_5,
    recursive_corpus: true,
    has_registry: true,
    extension: "xml",
    look_addons: false,
    look_mount: false,
    look_corpseactionid: false,
    // No `hostile` and no `staticattack` (`monsters.cpp:894`–`:934`).
    bool_flags: &[
        "attackable",
        "summonable",
        "convinceable",
        "illusionable",
        "challengeable",
        "pushable",
        "canpushitems",
        "canpushcreatures",
        "isboss",
        "ignorespawnblock",
        "hidehealth",
        "canwalkonenergy",
        "canwalkonfire",
        "canwalkonpoison",
    ],
    num_flags: &["targetdistance", "runonhealth", "lightlevel", "lightcolor"],
    dead_flags: &[],
    has_pacifist: false,
    // TVP dropped the override TFS and Ironcore both apply.
    pushable_override: PushableOverride::Never,
    clamps_health: true,
    immunities: IMMUNITIES_TVP,
    elements: ELEMENTS_6,
    target_strategy: Some(("targetstrategy", STRATEGY_KEYS)),
    target_strategy_sums_100: true,
    warns_missing_target_strategy: true,
    cadence: Cadence::IntervalOrDelay,
    builtin_spells: SPELLS_TVP,
    melee: MeleeKind::SpellBlock,
    melee_conditions: MELEE_COND_TVP,
    melee_skill_progression: true,
    geometry_ring: false,
    speed_spell: SpeedSpell::SpeedVariation,
    condition_spell: ConditionSpell::TickStartCycle,
    range_limit: RangeLimit::ClampTo(22),
    spell_range_default: 0,
    effect_naming: EffectNaming::ShortName,
    magic_effects: ME_7X,
    shoot_effects: ANI_TVP,
    spell_effect_keys: &["shootEffect", "areaEffect"],
    // TVP never iterates a summon's children.
    summon_effect_keys: &[],
    loot_inside_wrapper: true,
    loot_validates_ids: true,
    loot_countmax_max: None,
    warns_missing_targetchange_interval: false,
    summon_interval: true,
    summon_delay: true,
    summon_max_key: "max",
    summon_nested: false,
    // Both are commented out in the loader (`monsters.cpp:1142`).
    voices_interval: false,
    voices_chance: false,
    suppressed_lints: &[
        "flag.pacifist-forces-hostile-off",
        "flag.pacifist-subflag-without-pacifist",
        "flag.staticattack-over-100",
        "flags.hostile",
        "raceid.",
        "effect.knife-renders-pitchfork",
        "effect.unreachable",
        "voices.chance",
        "voices.chance-over-100",
    ],
};

pub static NOSTALRIUS: EngineProfile = EngineProfile {
    key: "nostalrius",
    format: Format::Xml,
    label: "Nostalrius",
    blurb: "7.x: melee on <attacks>, no spell interval, count= conditions",
    raceid_attr: None,
    has_species: false,
    has_bestiary: false,
    races: RACES_NOS,
    skulls: SKULLS_5,
    recursive_corpus: true,
    has_registry: true,
    extension: "xml",
    look_addons: false,
    look_mount: false,
    look_corpseactionid: false,
    bool_flags: &[
        "attackable",
        "hostile",
        "summonable",
        "convinceable",
        "illusionable",
        "pushable",
        "canpushitems",
        "canpushcreatures",
    ],
    num_flags: &["targetdistance", "runonhealth", "lightlevel", "lightcolor"],
    dead_flags: &[],
    has_pacifist: false,
    pushable_override: PushableOverride::Always,
    // Nostalrius has no `health now > max` warning at all (`monsters.cpp:635`).
    clamps_health: false,
    immunities: IMMUNITIES_NOS,
    elements: ELEMENTS_6,
    target_strategy: Some(("targetstrategy", STRATEGY_KEYS)),
    target_strategy_sums_100: false,
    warns_missing_target_strategy: true,
    cadence: Cadence::ChanceOnly,
    builtin_spells: SPELLS_NOS,
    melee: MeleeKind::AttacksNode,
    melee_conditions: &[],
    melee_skill_progression: false,
    geometry_ring: false,
    speed_spell: SpeedSpell::ChangeVariation,
    condition_spell: ConditionSpell::Count,
    range_limit: RangeLimit::ClampTo(22),
    // `sb.range = Map::maxClientViewportX` when absent (`monsters.cpp:289`).
    spell_range_default: 8,
    effect_naming: EffectNaming::ShortName,
    magic_effects: ME_7X,
    shoot_effects: ANI_NOS,
    spell_effect_keys: &["shootEffect", "areaEffect"],
    summon_effect_keys: &[],
    // `loadLootContainer` iterates children directly (`monsters.cpp:1054`).
    loot_inside_wrapper: false,
    // `lootBlock.id = cast(attr)` with no item lookup (`monsters.cpp:991`).
    loot_validates_ids: false,
    loot_countmax_max: None,
    warns_missing_targetchange_interval: true,
    summon_interval: false,
    summon_delay: false,
    summon_max_key: "max",
    summon_nested: false,
    voices_interval: false,
    voices_chance: false,
    suppressed_lints: &[
        "flag.pacifist-forces-hostile-off",
        "flag.pacifist-subflag-without-pacifist",
        "flag.staticattack-over-100",
        "raceid.",
        "effect.knife-renders-pitchfork",
        "effect.unreachable",
        "voices.chance",
        "voices.chance-over-100",
        "spell.interval-under-1",
        "spell.missing-chance",
        "manacost.zero-with-summonable",
    ],
};
pub static CANARY: EngineProfile = EngineProfile {
    key: "canary",
    label: "Canary / OTServBR",
    format: Format::Lua,
    blurb: "Lua monsters, bestiary + bosstiary, factions, COMBAT_* damage types",
    // `monster.raceId` is the bestiary key, but it is a Lua field rather than an
    // attribute — the reader picks it up by name, not through this.
    raceid_attr: None,
    has_species: false,
    has_bestiary: true,
    races: RACES_CANARY,
    skulls: SKULLS_7,
    recursive_corpus: true,
    has_registry: false,
    extension: "lua",
    look_addons: true,
    look_mount: true,
    look_corpseactionid: false,
    bool_flags: FLAGS_CANARY_BOOL,
    num_flags: FLAGS_CANARY_NUM,
    dead_flags: DEAD_FLAGS_CANARY,
    has_pacifist: false,
    pushable_override: PushableOverride::Never,
    clamps_health: true,
    immunities: IMMUNITIES_10,
    elements: ELEMENTS_10,
    target_strategy: Some(("strategiesTarget", STRATEGY_KEYS_CANARY)),
    target_strategy_sums_100: false,
    warns_missing_target_strategy: false,
    cadence: Cadence::Interval,
    builtin_spells: SPELLS_LUA,
    melee: MeleeKind::SpellBlock,
    melee_conditions: MELEE_COND_FULL,
    melee_skill_progression: false,
    geometry_ring: true,
    speed_spell: SpeedSpell::SpeedChange,
    condition_spell: ConditionSpell::TickStart,
    range_limit: RangeLimit::TruncateU8,
    spell_range_default: 0,
    // Effects are `CONST_ANI_*`/`CONST_ME_*` identifiers or bare numbers.
    effect_naming: EffectNaming::ConstMe,
    magic_effects: ME_CANARY,
    shoot_effects: ANI_CANARY,
    spell_effect_keys: &["shootEffect", "effect"],
    summon_effect_keys: &[],
    loot_inside_wrapper: false,
    loot_validates_ids: true,
    loot_countmax_max: None,
    warns_missing_targetchange_interval: false,
    summon_interval: true,
    summon_delay: false,
    summon_max_key: "count",
    summon_nested: true,
    voices_interval: true,
    voices_chance: true,
    suppressed_lints: &[
        // There is no spells.xml on these engines, so a name MONx does not
        // recognise cannot be checked against a registry — reporting it would
        // flag every scripted spell in the corpus.
        "spell.name-unverifiable",
        // Canary's bestiary difficulty is a numeric star rating, not TFS's
        // word list.
        "bestiary.unknown-difficulty",
        // No registry: every .lua under the folder is loaded, so a file cannot
        // be an orphan and there are no entries to dangle.
        "registry.",
        "flag.pacifist-forces-hostile-off",
        "flag.pacifist-subflag-without-pacifist",
        "effect.knife-renders-pitchfork",
        "effect.unreachable",
        // Attribute-casing traps are an XML concept.
        "loot.actionid-wrong-case",
        "summons.maxsummons-wrong-case",
        "raceid.wrong-case",
        // Presence rules that only `lint_source` can see, and it only sees XML.
        "health.missing-now",
        "health.missing-max",
        "spell.missing-chance",
        "targetchange.missing-interval",
        "targetchange.missing-chance",
        "voices.missing-interval",
        "voices.missing-chance",
        "summons.maxsummons-missing",
        "flag.multiple-attributes",
        "immunity.multiple-attributes",
        "element.multiple-attributes",
    ],
};

pub static BLACKTEK: EngineProfile = EngineProfile {
    key: "blacktek",
    label: "BlackTek",
    format: Format::Lua,
    blurb: "TFS 1.x in Lua: flags table, top-level numerics, custom skills",
    raceid_attr: None,
    has_species: false,
    has_bestiary: false,
    races: RACES_TFS,
    skulls: SKULLS_7,
    recursive_corpus: true,
    has_registry: false,
    extension: "lua",
    look_addons: true,
    look_mount: true,
    look_corpseactionid: false,
    bool_flags: FLAGS_BLACKTEK_BOOL,
    num_flags: FLAGS_BLACKTEK_NUM,
    dead_flags: &[],
    has_pacifist: false,
    pushable_override: PushableOverride::OnlyWhenUnset,
    clamps_health: true,
    immunities: IMMUNITIES_10,
    elements: ELEMENTS_10,
    target_strategy: None,
    target_strategy_sums_100: false,
    warns_missing_target_strategy: false,
    cadence: Cadence::Interval,
    builtin_spells: SPELLS_LUA,
    melee: MeleeKind::SpellBlock,
    melee_conditions: MELEE_COND_FULL,
    melee_skill_progression: false,
    geometry_ring: true,
    speed_spell: SpeedSpell::SpeedChange,
    condition_spell: ConditionSpell::TickStart,
    range_limit: RangeLimit::TruncateU8,
    spell_range_default: 0,
    effect_naming: EffectNaming::ConstMe,
    magic_effects: ME_BLACKTEK,
    shoot_effects: ANI_BLACKTEK,
    spell_effect_keys: &["shootEffect", "effect"],
    summon_effect_keys: &[],
    loot_inside_wrapper: false,
    loot_validates_ids: true,
    loot_countmax_max: None,
    warns_missing_targetchange_interval: false,
    summon_interval: true,
    summon_delay: false,
    summon_max_key: "max",
    summon_nested: false,
    voices_interval: true,
    voices_chance: true,
    suppressed_lints: &[
        "spell.name-unverifiable",
        "registry.",
        "raceid.",
        "flag.pacifist-forces-hostile-off",
        "flag.pacifist-subflag-without-pacifist",
        "effect.knife-renders-pitchfork",
        "effect.unreachable",
        "loot.actionid-wrong-case",
        "summons.maxsummons-wrong-case",
        "health.missing-now",
        "health.missing-max",
        "spell.missing-chance",
        "targetchange.missing-interval",
        "targetchange.missing-chance",
        "voices.missing-interval",
        "voices.missing-chance",
        "summons.maxsummons-missing",
        "flag.multiple-attributes",
        "immunity.multiple-attributes",
        "element.multiple-attributes",
    ],
};

/// CrystalServer is a Canary fork, and the fork line runs almost exactly where
/// the monster layer ends: `data/libs/functions/revscriptsys.lua` — the file
/// that turns `monster.*` table keys into `MonsterType` setter calls — is byte
/// for byte the same in both trees, and a Crystal monster file is a Canary
/// monster file. Four things make it its own profile rather than an alias:
///
/// - **Effect names.** Crystal renamed magic-effect ids 269 and 272–303 in
///   place. Canary's spellings would write identifiers Crystal has never heard
///   of, and the picker is the whole point of having the table.
/// - **`skull`.** Canary registers no skull setter, so `lint.rs` errors on the
///   field there; Crystal registers one (`monster_type_functions.cpp`), so the
///   field is real and the lint must not fire.
/// - **`COMBAT_AGONYDAMAGE`.** An eleventh damage type, used by eleven monsters
///   in the shipped corpus. Without it in `elements` the writer drops those
///   entries on save, which is the one failure mode this file exists to prevent.
/// - **Five new shoot effects** (the storm arrows, 64–68).
///
/// Everything else — the flags table, `strategiesTarget`, the bestiary and
/// bosstiary blocks, sounds, the loot shape — is Canary's, so this is a copy of
/// `CANARY` with those four edits and nothing else.
pub static CRYSTAL: EngineProfile = EngineProfile {
    key: "crystal",
    label: "CrystalServer",
    format: Format::Lua,
    blurb: "Canary fork: renamed effect constants, agony damage, skull setter",
    raceid_attr: None,
    has_species: false,
    has_bestiary: true,
    races: RACES_CANARY,
    skulls: SKULLS_7,
    recursive_corpus: true,
    has_registry: false,
    extension: "lua",
    look_addons: true,
    look_mount: true,
    look_corpseactionid: false,
    bool_flags: FLAGS_CRYSTAL_BOOL,
    num_flags: FLAGS_CANARY_NUM,
    dead_flags: DEAD_FLAGS_CANARY,
    has_pacifist: false,
    pushable_override: PushableOverride::Never,
    clamps_health: true,
    immunities: IMMUNITIES_CRYSTAL,
    elements: ELEMENTS_CRYSTAL,
    target_strategy: Some(("strategiesTarget", STRATEGY_KEYS_CANARY)),
    target_strategy_sums_100: false,
    warns_missing_target_strategy: false,
    cadence: Cadence::Interval,
    builtin_spells: SPELLS_LUA,
    melee: MeleeKind::SpellBlock,
    melee_conditions: MELEE_COND_FULL,
    melee_skill_progression: false,
    geometry_ring: true,
    speed_spell: SpeedSpell::SpeedChange,
    condition_spell: ConditionSpell::TickStart,
    range_limit: RangeLimit::TruncateU8,
    spell_range_default: 0,
    effect_naming: EffectNaming::ConstMe,
    magic_effects: ME_CRYSTAL,
    shoot_effects: ANI_CRYSTAL,
    spell_effect_keys: &["shootEffect", "effect"],
    summon_effect_keys: &[],
    loot_inside_wrapper: false,
    loot_validates_ids: true,
    loot_countmax_max: None,
    warns_missing_targetchange_interval: false,
    summon_interval: true,
    summon_delay: false,
    summon_max_key: "count",
    summon_nested: true,
    voices_interval: true,
    voices_chance: true,
    // Canary's list verbatim. `lua.skull-unsupported` is not here because it is
    // keyed on the Canary profile itself and never fires for Crystal.
    suppressed_lints: &[
        "spell.name-unverifiable",
        "bestiary.unknown-difficulty",
        "registry.",
        "flag.pacifist-forces-hostile-off",
        "flag.pacifist-subflag-without-pacifist",
        "effect.knife-renders-pitchfork",
        "effect.unreachable",
        "loot.actionid-wrong-case",
        "summons.maxsummons-wrong-case",
        "raceid.wrong-case",
        "health.missing-now",
        "health.missing-max",
        "spell.missing-chance",
        "targetchange.missing-interval",
        "targetchange.missing-chance",
        "voices.missing-interval",
        "voices.missing-chance",
        "summons.maxsummons-missing",
        "flag.multiple-attributes",
        "immunity.multiple-attributes",
        "element.multiple-attributes",
    ],
};

pub static ALL: &[&EngineProfile] = &[
    &IRONCORE,
    &TFS,
    &TVP,
    &NOSTALRIUS,
    &CANARY,
    &CRYSTAL,
    &BLACKTEK,
];

pub fn by_key(key: &str) -> Option<&'static EngineProfile> {
    ALL.iter().copied().find(|p| p.key == key)
}

/// The profile to fall back to when nothing is specified and nothing detects.
pub fn default_profile() -> &'static EngineProfile {
    &IRONCORE
}

